# Host to use for canonical URL generation (without trailing slash)
host: louises-gds-way.cloudapps.digital
service_link: /

# Header-related options
show_govuk_logo: false
service_name: Defo NOT the GDS Way
description: An attempt to rejig the content on the GDS Way. The GDS Way is technical standards and guidance used by teams building software at GDS

# Links to show on right-hand-side of header
header_links:
  Documentation: /
  GitHub: https://github.com/louzoid-gds/defo-not-the-gds-way
  The real GDS Way: https://gds-way.cloudapps.digital/

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: louzoid-gds/defo-not-the-gds-way
